repos:
  - repo: https://github.com/python/black
    rev: 19.10b0
    hooks:
      - id: black
        pass_filenames: true
  - repo: https://gitlab.com/pycqa/flake8
    rev: "3.8.3"
    hooks:
      - id: flake8
        pass_filenames: true
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v0.782"
    hooks:
      - id: mypy
        args: [--ignore-missing-imports, --no-implicit-reexport]